<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/PrecisionLab.Acquisition/PrecisionLab.Acquisition.csproj" />
    <ProjectReference Include="../../src/PrecisionLab.Contracts/PrecisionLab.Contracts.csproj" />
    <ProjectReference Include="../../src/PrecisionLab.Drivers.Builtin/PrecisionLab.Drivers.Builtin.csproj" />
  </ItemGroup>
</Project>
