<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="IviFoundation.Visa" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../PrecisionLab.Domain/PrecisionLab.Domain.csproj" />
    <ProjectReference Include="../PrecisionLab.Drivers.Abstractions/PrecisionLab.Drivers.Abstractions.csproj" />
  </ItemGroup>
</Project>
